[toolchain]
anchor_version = "0.31.1"


package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
my_counter = "pCS5uh7FCBpPW1QScvWm2KywX78khpPiKJ8RkpyNfpe"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
